name: timostestapp3
version: '0.0.1~test'
summary: Upstream Qt to be compiled as part of your project
description: |
  Qt is a cross-platform C++ application framework. Qt's primary feature
  is its rich set of widgets that provide standard GUI functionality.
  This package includes several Qt Project's Qt modules as is from upstream.

grade: stable
confinement: strict

plugs:
  ubuntu-qt-runtime:
      content: ubuntu-qt-runtime
      interface: content
      target: ubuntu-qt-runtime

parts:
  qtapp2:
    plugin: qmake
    qt-version: qt5
    source: .
    # Not suitable for cleanbuild at the moment
    build-packages: []
        #- qtbase5-dev
        #- qtdeclarative5-dev
        #- qt5-qmake
        #- qt5-default
        #- g++
    stage-packages: []
    filesets:
         includedfiles:
             - "backend/*"
             - "bin/*"
             - "qtapp2/*"
             - "Qtapp2/*"
             - "ubuntu-qt-runtime/*"
             - "-usr/*"
    snap:
         - "$includedfiles"

  launcher:
    plugin: dump
    source: .
    organize:
      launcher: bin/qtapp2.run

apps:
  timostestapp3:
    command: bin/qtapp2.run
    plugs: ['ubuntu-qt-runtime', 'home', 'unity7', 'opengl']
